-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 19:08:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pizzaria_legal`.`tb_pizza` ;

CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ingredientes` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `sabor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pizzaria_legal`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `borda` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza_has_tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` ;

CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (
  `tb_pizza_id_pizza` INT NOT NULL,
  `tb_categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`),
  INDEX `fk_tb_pizza_has_tb_categoria_tb_categoria1_idx` (`tb_categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_tb_pizza_has_tb_categoria_tb_pizza_idx` (`tb_pizza_id_pizza` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_has_tb_categoria_tb_pizza`
    FOREIGN KEY (`tb_pizza_id_pizza`)
    REFERENCES `db_pizzaria_legal`.`tb_pizza` (`id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pizza_has_tb_categoria_tb_categoria1`
    FOREIGN KEY (`tb_categoria_id_categoria`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_pizzaria_legal`;
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'napolitana', 'muçarela, tomate, oregano, molho de tomate e azeitonas', 'vegetariana', 'salgada');
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'calabresa', 'calabresa fatiada, cebola, molho de tomate e azeitonas', 'não-vegetariana', 'salgada');
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'atum', 'atum ralado, cebola, molho de tomate e azeitonas', 'não-vegetariana', 'salgada');
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'vegana', 'palmito, rúcula, cebolinha, molho de tomate e azeitonas', 'vegana', 'salgada');
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'frango', 'frago desfiado temperado, molho de tomate e azeitonas', 'não-vegetariana', 'salgada');
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'romeu e julieta', 'muçarela e goiabada', 'vegetariana', 'doce');
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'chocolate', 'chocolate harald com granulado ou coco ralado', 'não-vegetariana', 'doce');
INSERT INTO `db_pizzaria_legal`.`tb_pizza` (`id_pizza`, `nome`, `ingredientes`, `tipo`, `sabor`) VALUES (DEFAULT, 'banana', 'banana, leite condensado e canela', 'vegetariana', 'doce');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_pizzaria_legal`;
INSERT INTO `db_pizzaria_legal`.`tb_categoria` (`id_categoria`, `tamanho`, `preco`, `borda`) VALUES (DEFAULT, 'pequena (broto) - 4 pedacos', 28, false);
INSERT INTO `db_pizzaria_legal`.`tb_categoria` (`id_categoria`, `tamanho`, `preco`, `borda`) VALUES (DEFAULT, 'media - 8 pedacos', 45, false);
INSERT INTO `db_pizzaria_legal`.`tb_categoria` (`id_categoria`, `tamanho`, `preco`, `borda`) VALUES (DEFAULT, 'media - 8 pedacos', 49, true);
INSERT INTO `db_pizzaria_legal`.`tb_categoria` (`id_categoria`, `tamanho`, `preco`, `borda`) VALUES (DEFAULT, 'grande - 12 pedacos', 56, false);
INSERT INTO `db_pizzaria_legal`.`tb_categoria` (`id_categoria`, `tamanho`, `preco`, `borda`) VALUES (DEFAULT, 'grande - 12 pedacos', 60, true);

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_pizzaria_legal`.`tb_pizza_has_tb_categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_pizzaria_legal`;
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (1, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (1, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (1, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (1, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (1, 5);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (2, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (2, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (2, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (2, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (2, 5);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (3, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (3, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (3, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (3, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (3, 5);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (4, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (4, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (4, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (4, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (4, 5);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (5, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (5, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (5, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (5, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (5, 5);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (6, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (6, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (6, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (6, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (6, 5);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (7, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (7, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (7, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (7, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (7, 5);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (8, 1);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (8, 2);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (8, 3);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (8, 4);
INSERT INTO `db_pizzaria_legal`.`tb_pizza_has_tb_categoria` (`tb_pizza_id_pizza`, `tb_categoria_id_categoria`) VALUES (8, 5);

COMMIT;

