-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 16:39:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_generation_game_online`.`tb_classe` ;

CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `id_classe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_generation_game_online`.`tb_personagem` ;

CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `id_personagem` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NOT NULL,
  `ataque` BIGINT(10) NOT NULL,
  `defesa` BIGINT(10) NOT NULL,
  `inteligencia` BIGINT(10) NOT NULL,
  `destreza` BIGINT(10) NOT NULL,
  `agilidade` BIGINT(10) NOT NULL,
  `fk_classe` INT NOT NULL,
  PRIMARY KEY (`id_personagem`, `fk_classe`),
  INDEX `fk_tb_personagem_tb_classe_idx` (`fk_classe` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`fk_classe`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_generation_game_online`;
INSERT INTO `db_generation_game_online`.`tb_classe` (`id_classe`, `nome`) VALUES (DEFAULT, 'gatuno');
INSERT INTO `db_generation_game_online`.`tb_classe` (`id_classe`, `nome`) VALUES (DEFAULT, 'mago');
INSERT INTO `db_generation_game_online`.`tb_classe` (`id_classe`, `nome`) VALUES (DEFAULT, 'guerreiro');
INSERT INTO `db_generation_game_online`.`tb_classe` (`id_classe`, `nome`) VALUES (DEFAULT, 'arqueiro');
INSERT INTO `db_generation_game_online`.`tb_classe` (`id_classe`, `nome`) VALUES (DEFAULT, 'sacerdote');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_generation_game_online`;
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'jplb', 3000, 2000, 3000, 0, 2000, 2);
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'dada', 1000, 3000, 3000, 0, 3000, 5);
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'lena', 3000, 3000, 0, 1000, 3000, 3);
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'joca', 1000, 1000, 0, 3000, 5000, 4);
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'sally', 2000, 2000, 0, 3000, 3000, 3);
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'silva', 4000, 1000, 0, 0, 5000, 3);
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'thi', 5000, 0, 0, 1000, 4000, 1);
INSERT INTO `db_generation_game_online`.`tb_personagem` (`id_personagem`, `nick`, `ataque`, `defesa`, `inteligencia`, `destreza`, `agilidade`, `fk_classe`) VALUES (DEFAULT, 'beto', 3000, 3000, 1000, 1000, 2000, 2);

COMMIT;

