-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 22:22:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_eCommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_eCommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_eCommerce` DEFAULT CHARACTER SET utf8 ;
USE `db_eCommerce` ;

-- -----------------------------------------------------
-- Table `db_eCommerce`.`tb_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_eCommerce`.`tb_produtos` ;

CREATE TABLE IF NOT EXISTS `db_eCommerce`.`tb_produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `qtdEstoque` INT(9) NOT NULL,
  `preço` DECIMAL(10,2) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_eCommerce`.`tb_produtos`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_eCommerce`;
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'borracha', 500, 1.00, 'branca', 1);
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'caneta', 150, 1.50, 'azul', 1);
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'caneta', 150, 1.50, 'preta', 1);
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'caneta', 150, 1.50, 'vermelha', 1);
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'caneta', 150, 1.50, 'verde', 1);
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'lápis', 150, 0.50, 'preto', 1);
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'fichário', 30, 70.00, 'colorido', 1);
INSERT INTO `db_eCommerce`.`tb_produtos` (`id_produto`, `nome`, `qtdEstoque`, `preço`, `cor`, `ativo`) VALUES (DEFAULT, 'mochila para notebook', 20, 150, 'prata', 1);

COMMIT;

