-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 20:23:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_RH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_RH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_RH` DEFAULT CHARACTER SET utf8 ;
USE `db_RH` ;

-- -----------------------------------------------------
-- Table `db_RH`.`tb_funcionaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_RH`.`tb_funcionaries` ;

CREATE TABLE IF NOT EXISTS `db_RH`.`tb_funcionaries` (
  `id_funcionarie` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` BIGINT(11) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `matricula` INT(9) NOT NULL,
  PRIMARY KEY (`id_funcionarie`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_RH`.`tb_funcionaries`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_RH`;
INSERT INTO `db_RH`.`tb_funcionaries` (`id_funcionarie`, `nome`, `cpf`, `cargo`, `salario`, `matricula`) VALUES (DEFAULT, 'João', 12345678901, 'Desenvolvedor Java Junior', 5000.00, 202111222);
INSERT INTO `db_RH`.`tb_funcionaries` (`id_funcionarie`, `nome`, `cpf`, `cargo`, `salario`, `matricula`) VALUES (DEFAULT, 'Maria', 98765432101, 'Analista de Sistemas Juniior', 1999.00, 202122333);
INSERT INTO `db_RH`.`tb_funcionaries` (`id_funcionarie`, `nome`, `cpf`, `cargo`, `salario`, `matricula`) VALUES (DEFAULT, 'Eduarda', 31343234432, 'Coordenadora de Sistemas', 6000.00, 202133444);
INSERT INTO `db_RH`.`tb_funcionaries` (`id_funcionarie`, `nome`, `cpf`, `cargo`, `salario`, `matricula`) VALUES (DEFAULT, 'Pedro', 12313713792, 'Desenvolvedor Java Pleno', 8000.00, 202144555);
INSERT INTO `db_RH`.`tb_funcionaries` (`id_funcionarie`, `nome`, `cpf`, `cargo`, `salario`, `matricula`) VALUES (DEFAULT, 'Joaquina', 63248724682, 'Desenvolvedor Java Senior', 10000.00, 202155666);

COMMIT;

