-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 22:16:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_escola` DEFAULT CHARACTER SET utf8 ;
USE `db_escola` ;

-- -----------------------------------------------------
-- Table `db_escola`.`tb_alunes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_alunes` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_alunes` (
  `id_alune` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `matrícula` BIGINT(9) NOT NULL,
  `nota` FLOAT NOT NULL,
  `cpf` BIGINT(11) NOT NULL,
  `gênero` VARCHAR(30) NULL,
  PRIMARY KEY (`id_alune`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_escola`.`tb_alunes`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_escola`;
INSERT INTO `db_escola`.`tb_alunes` (`id_alune`, `nome`, `matrícula`, `nota`, `cpf`, `gênero`) VALUES (DEFAULT, 'João', 202111222, 10, 25364718342, 'masculino');
INSERT INTO `db_escola`.`tb_alunes` (`id_alune`, `nome`, `matrícula`, `nota`, `cpf`, `gênero`) VALUES (DEFAULT, 'Rivelino', 202122333, 7, 16354789234, 'masculino');
INSERT INTO `db_escola`.`tb_alunes` (`id_alune`, `nome`, `matrícula`, `nota`, `cpf`, `gênero`) VALUES (DEFAULT, 'Isac', 202133444, 7, 16342547365, 'não-binário');
INSERT INTO `db_escola`.`tb_alunes` (`id_alune`, `nome`, `matrícula`, `nota`, `cpf`, `gênero`) VALUES (DEFAULT, 'Liz', 202144555, 5, 63425374912, 'feminino');
INSERT INTO `db_escola`.`tb_alunes` (`id_alune`, `nome`, `matrícula`, `nota`, `cpf`, `gênero`) VALUES (DEFAULT, 'Babiy', 202155666, 3, 17354627453, 'feminino');

COMMIT;

